# This is a basic workflow to help you get started with Actions

name: UUP dump build

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DOWNLOAD_URL:
        description: 'DOWNLOAD_URL'
        required: true
        default: 'https://github.com/mi20210630/uup_dump_wnc_action/releases/download/ready-pack/26100.2314_arm64_en-us_wnc_6b214305_convert.zip'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get ready
        run: |
          wget -O build.zip ${{ github.event.inputs.DOWNLOAD_URL }}
          unzip build.zip -d run
          sudo apt update
          sudo apt install cabextract

      - name: Run build
        run: |
          cd run
          bash uup_download_linux.sh
          
      - name: Upload to Release‌‌
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "${{ github.workspace }}/run/*.iso"
          token: ${{ secrets.TOKEN }}
