# This is a basic workflow to help you get started with Actions

name: UUP dump build

# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DOWNLOAD_URL:
        description: 'DOWNLOAD_URL'
        required: true
        default: 'https://uupdump.net/get.php?id=6b214305-5bc5-4904-a751-ea237c62f6ac&pack=en-us&edition=wnc'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Download
        run: wget -O build.zip ${{ github.event.inputs.DOWNLOAD_URL }} && unzip build.zip -d run

      # Runs a set of commands using the runners shell
      - name: Run build
        run: |
          cd run
          bash uup_download_linux.sh
          
      - name: Upload to Release‌‌
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "${{ github.workspace }}/run/*.iso"
          token: ${{ secrets.TOKEN }}
